version: "3"
services:
  trans:
    stdin_open: true
    tty: true
    container_name: en2zh
    environment:
      - APPID=xxxxxxxxxxxxxxxxx
      - KEY=xxxxxxxxxxxxxxxxxxxx
      - FROM=en
      - TO=zh-CN
      - PROXY=192.168.1.20:8889
    volumes:
      - /d/srt:/srt
      - /d/database:/data
    privileged: true
    network_mode: host
    image: trans:v4
#    command: ash